name: nombre_de_tu_proyecto
description: Una breve descripción de tu proyecto
version: 1.0.0

environment:
  sdk:  ^3.0.0
dependencies:
  http: ^0.13.6

  # Agrega otras dependencias según sea necesario


